#!/usr/bin/env ruby

require "clipboard"

Clipboard.copy("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")
puts ARGV[0]

system("git add .")
system("git commit -m #{ARGV[0]}")
system("git push -u origin main")
